# название вашего action
name: Semgrep
# условия выполнения action - при внесении изменений в ветки main и test
on:
  push:
    branches:
    - main
    - dev
# содержание action - создание и выполнение контейнера с анализатором semgrep
jobs:
  semgrep:
    name: semgrep/ci
    runs-on: ubuntu-latest
    container:
      image: semgrep/Semgrep
  steps:
  - uses: actions/checkout@v4
  - run: semgrep ci
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }} # секрет из нашего репозитория
